Host joplin-backup-router
  HostName 192.168.3.226
  Port 61622
  User joplin-backup-jump
  IdentityFile /etc/joplin-server/ssh/joplin-backup-ed25519
  IdentitiesOnly yes
  UserKnownHostsFile /etc/joplin-server/ssh/known_hosts
  GlobalKnownHostsFile /dev/null
  StrictHostKeyChecking yes
  BatchMode yes
  RequestTTY no

Host joplin-backup-nas
  HostName 192.168.5.170
  Port 22
  User joplin-backup
  ProxyJump joplin-backup-router
  IdentityFile /etc/joplin-server/ssh/joplin-backup-ed25519
  IdentitiesOnly yes
  UserKnownHostsFile /etc/joplin-server/ssh/known_hosts
  GlobalKnownHostsFile /dev/null
  StrictHostKeyChecking yes
  BatchMode yes
  RequestTTY no
