Match User joplin-backup-jump
  AuthorizedKeysFile /etc/ssh/authorized_keys/joplin-backup-jump
  AuthenticationMethods publickey
  PasswordAuthentication no
  KbdInteractiveAuthentication no
  AllowAgentForwarding no
  AllowTcpForwarding local
  AllowStreamLocalForwarding no
  PermitOpen 192.168.5.170:22
  X11Forwarding no
  PermitTTY no
  PermitTunnel no
  ForceCommand /usr/bin/false
