Match User joplin-backup
  ChrootDirectory /volume1/Backups/joplin-server
  ForceCommand internal-sftp -d /repo
  AuthorizedKeysFile /etc/ssh/authorized_keys/joplin-backup
  AuthenticationMethods publickey
  PasswordAuthentication no
  KbdInteractiveAuthentication no
  AllowAgentForwarding no
  AllowTcpForwarding no
  AllowStreamLocalForwarding no
  X11Forwarding no
  PermitTTY no
  PermitTunnel no
